### ISSUE TITLE
Add an option to remove your rating on a map

### ISSUE THREAD

**Issue by totallywaffles** [apollo-dw/omdb#12]
Right now if you accidently rate a map you can only change your rating, not remove it, which is a problem if you've never played the map. 

For the UI I suggest an X to the right of the 5 stars you can click.

**Comment by apollo-dw** [comment]
are you on mobile? there is a rating removal button that appears on hover on desktop 
![image](https://user-images.githubusercontent.com/83023433/209484370-da4addd9-7152-4211-ba72-5e1f4eae136e.png)

maybe i can make it be always visible

**Comment by totallywaffles** [comment]
yes I'm on mobile, my bad. always visible on mobile would be good.

**Comment by apollo-dw** [comment]
should be better now 👀
