### ISSUE TITLE
Display usernames next to avatars everywhere

### ISSUE THREAD

**Issue by venix12** [apollo-dw/omdb#16]
Currently is a thing for comment headers only and i believe website would vastly improve its readability if done in other places like homepage or latest ratings

**Comment by apollo-dw** [comment]
The reason why it's not being shown on the front page currently is for space limitation reasons - although I agree the readability would be better. I'll need to think about what can I do to conserve space to accomodate for this

**Comment by VINXIS** [comment]
the tooltip helps a lot but ia lso think itd be better to just show the username as well like maybe on top of the comment/rating or some shit

**Comment by apollo-dw** [comment]
I've implemented this. Let's see how it feels once everyone gets used to it.
