### ISSUE TITLE
Add ability to rate users

### ISSUE THREAD

**Issue by venix12** [apollo-dw/omdb#17]
Users rating would be kinda interesting in addition to the current beatmap-only system I believe, even if possibly a thing to be done in longer future.

**Comment by apollo-dw** [comment]
Leaning towards not wanting to do this... seems outside of the scope of the site + I can only see this being used negatively

**Comment by VINXIS** [comment]
yea i think this shouldnt happen either

**Comment by apollo-dw** [comment]
closing as not planned
