### ISSUE TITLE
Add ability to sort user's ratings

### ISSUE THREAD

**Issue by venix12** [apollo-dw/omdb#18]
![image](https://user-images.githubusercontent.com/30481900/209674911-74cbb4a1-20f7-4470-86b8-ea68b331bd76.png)

Would be real nice to be able to show highest 50 / lowest 50 or something here I believe.

**Comment by apollo-dw** [comment]
can you clarify what you mean by highest/lowest 50?

**Comment by apollo-dw** [comment]
you can theoretically do this now by going to the ratings page, selecting `Highest rated` and `All` ratings, so...
