### ISSUE TITLE
Missing beatmaps

### ISSUE THREAD

**Issue by apollo-dw** [apollo-dw/omdb#2]
spme maps are missing because of the initial import process being Suboptimal, so i need to fix missing maps manually.

post links here and i'll do them ASAP, will react with something once its done

**Comment by Uberzolik** [comment]
https://osu.ppy.sh/beatmapsets/408745

**Comment by VINXIS** [comment]
https://omdb.nyahh.net/mapset/1674914 missing diffs

**Comment by VINXIS** [comment]
https://omdb.nyahh.net/mapset/1880652

**Comment by VINXIS** [comment]
https://osu.ppy.sh/beatmapsets/409345#osu/888621

**Comment by XeKrOsu** [comment]
https://osu.ppy.sh/beatmapsets/660238#osu/1398077

**Comment by TidyBog305** [comment]
https://osu.ppy.sh/beatmapsets/537048#osu/1529760

**Comment by Serwaj123** [comment]
https://osu.ppy.sh/beatmapsets/683828#osu/1447280

**Comment by thunderbird2678** [comment]
https://osu.ppy.sh/beatmapsets/1066631#osu/2233313

**Comment by ILoveDorchadas** [comment]
https://osu.ppy.sh/beatmapsets/712974#osu/1506910

**Comment by Emil-bus** [comment]
https://omdb.nyahh.net/mapset/1418400

**Comment by doggoboat** [comment]
https://osu.ppy.sh/beatmapsets/1166022#osu/2431862

**Comment by doggoboat** [comment]
https://osu.ppy.sh/beatmapsets/365053#osu/801303

**Comment by doggoboat** [comment]
https://osu.ppy.sh/beatmapsets/446027/#osu/958038

**Comment by over-loadcode** [comment]
https://osu.ppy.sh/beatmapsets/1029440#osu/2152649

**Comment by VINXIS** [comment]
https://osu.ppy.sh/beatmapsets/995205
https://osu.ppy.sh/beatmapsets/442278

**Comment by Emil-bus** [comment]
https://osu.ppy.sh/beatmapsets/1129819

**Comment by happysatoko** [comment]
https://omdb.nyahh.net/mapset/845013 missing diffs

**Comment by happysatoko** [comment]
https://omdb.nyahh.net/mapset/54727

**Comment by happysatoko** [comment]
https://omdb.nyahh.net/mapset/953256

**Comment by happysatoko** [comment]
https://omdb.nyahh.net/mapset/1583099 
time travelling map

**Comment by VINXIS** [comment]
https://omdb.nyahh.net/mapset/115246

**Comment by tilda** [comment]
https://omdb.nyahh.net/mapset/136632 missing diffs

(btw please pin this issue)

**Comment by Emil-bus** [comment]
https://osu.ppy.sh/beatmapsets/1023428#osu/2157973
https://osu.ppy.sh/beatmapsets/1090194#osu/2279105
https://osu.ppy.sh/beatmapsets/1146874#osu/2394731

**Comment by apollo-dw** [comment]
Closing this as the apiv2 switch should have gotten everything again

**Comment by apollo-dw** [comment]
test

**Comment by apollo-dw** [comment]
test
