### ISSUE TITLE
Add average rating on user profile

### ISSUE THREAD

**Issue by venix12** [apollo-dw/omdb#20]

**Comment by apollo-dw** [comment]
the average rating that the user has given out, or the average rating of the player's beatmaps?

**Comment by venix12** [comment]
the first, 2nd is probably a topic for different issue

**Comment by Luminiscental** [comment]
I think the 2nd is more interesting (1st u can kinda just see from the distribution display already), and maybe even having charts of mappers by the average ratings of their maps could be cool (although I can think of reasons it'd be a bad idea).

**Comment by apollo-dw** [comment]
now added in "stats" tab on profile
