### ISSUE TITLE
Comments with angle bracket get trimmed

### ISSUE THREAD

**Issue by apollo-dw** [apollo-dw/omdb#3]
test case: `abc <90 def`, comments as `abc`

**Comment by Luminiscental** [comment]
Also comments with apostrophes; `ab'xy` comments as `ab`

**Comment by Luminiscental** [comment]
also `+` gets replaced by spaces; `a+b+c` comments as `a b c`

**Comment by VINXIS** [comment]
' shows as &#39; now

**Comment by apollo-dw** [comment]
fixed

**Comment by Luminiscental** [comment]
> Also + gets replaced by spaces; a+b+c comments as a b c

@apollo-dw this one has not been fixed
