### ISSUE TITLE
Searchbox isn't flexible enough

### ISSUE THREAD

**Issue by NeilPerry1** [apollo-dw/omdb#32]
There are some problems with yours searchbox on header. So a simple example: you cant search with full ASCII symbols like "-" and you cant search beatmap with logic "songname -> artist". Guess you can try natural langueage mode with full text on your DB or create odd concat table for searchbox.

**Comment by apollo-dw** [comment]
the search needs an overhaul so badly, the current effort is a naive one since it was the first time making one for any of my projects. if you could provide some links or resources to the things ur mentioning there then 👀

**Comment by NeilPerry1** [comment]
Sadly i have no idea how yours schema looks on mysql side and what responds in JSON from OSU API. Guess could try MATCH query instead of LIKE in "beatmapSearch.php row: 31". Its not cool deicision but could work for primitive search. https://dev.mysql.com/doc/refman/8.0/en/fulltext-natural-language.html


As example for test:

$stmt = $conn->prepare("SELECT `SetID`, Title, Artist, DifficultyName FROM `beatmaps` WHERE MATCH (DifficultyName, Artist, Title) AGAINST(? IN NATURAL LANGUAGE MODE) AND Mode='0' ORDER...

And also could cast values in lower register.

**Comment by apollo-dw** [comment]
this has now been added 🙏

**Comment by NeilPerry1** [comment]
In a futher if you will have a problems with searchbox (potentialy high que with many users/overloaded nodes or  beatmaps data becomes larger and larger) you can try to setup elasticsearch to yours db https://www.cloudways.com/blog/setup-elasticsearch-with-mysql/
