### ISSUE TITLE
Convert OMDB & osu! links to clickable links

### ISSUE THREAD

**Issue by apollo-dw** [apollo-dw/omdb#36]
![image](https://user-images.githubusercontent.com/83023433/212487067-d15c7cf7-da4b-4e08-ad19-a40eef19484b.png)

text could be turned into:
- osu link => `/s/999999`
- omdb link => `/mapset/999999`

every link should be clickable tbh

**Comment by tilda** [comment]
i have this map link regex from an old project, might take this up (and i could get it fixed up to take omdb links as well, likely)

![image](https://user-images.githubusercontent.com/8301262/216001426-a38acbfa-5ec8-405a-bb44-04a9c5e13d0b.png)

**Comment by apollo-dw** [comment]
test

**Comment by apollo-dw** [comment]
I've added this + OMDB link support - thank you @tilda for the regex :D
