### ISSUE TITLE
Beatmap recommendations

### ISSUE THREAD

**Issue by apollo-dw** [apollo-dw/omdb#40]
Users who rated `XXXXX [YYYYYY]` highly, also rated `AAAAA [BBBBBB]` highly.

https://www.geeksforgeeks.org/item-to-item-based-collaborative-filtering/
Item-to-item-based collaborative filtering might be useful here. I think running the algorithm as a cron on each beatmap with more than `N` (probably like 10 tbh) ratings once every day would work here - I am assuming the algorithm is expensive here. 

Also unsure on how to store the data for this...

**Comment by j-b-z** [comment]
OMDB WILL SOLVE THE OSU CONTENT CURATION ISSUE

**Comment by VINXIS** [comment]
if u use correlation instead of cosine similarity thatd be cool and consistent with tghe thing taht shows up on profiles but depends on the results ig

**Comment by NeilPerry1** [comment]
Guess it needs more complex approach. Firstly its hard to approximate how far this project goes. Secondary it needs side storage (columnar db like greenplum/etc or nosql database). Popular set i found is: Larevel as a transactor -> Kafka as a broker -> MongDB as a calculator+warehous cluster which back results on a front.

I'm bad at backend approaches but guess it's easiest way for implementation.

**Comment by apollo-dw** [comment]
I guess I can resolve this finally 😁
