### ISSUE TITLE
[Charts] Add Language filter

### ISSUE THREAD

**Issue by j-b-z** [apollo-dw/omdb#42]
Language filter from mapset metadata is notibly missing from chart filters. Hopefully it should be easy to add

<img width="265" alt="image" src="https://user-images.githubusercontent.com/22646945/214651528-1922037a-4ee1-4a21-a9c0-fd407e249e70.png">

**Comment by apollo-dw** [comment]
![image](https://user-images.githubusercontent.com/83023433/229360812-5b92df58-1633-43d6-80ec-50228f519bf7.png)

This has now been added
