### ISSUE TITLE
Punctuation breaks custom rating names

### ISSUE THREAD

**Issue by Luminiscental** [apollo-dw/omdb#46]
If I set a custom rating name as `a,b` then the comma disappears, `b` gets pushed into the next lower rating, and all lower rating names are shifted downwards. Also `a+b` turns into `a b`.

**Comment by apollo-dw** [comment]
The + thing is definitely going to be related to URL encoding, whereas the comma thing is just me being stupid 😅... storing the rating names in an array and converting it to a string turns it into a comma-separated value, so adding a comma in a rating name would obviously disrupt that

https://github.com/apollo-dw/omdb/blob/0af037fa30a3ec0348abe57d038ca779811b3e7f/settings/index.php#L122-L149
