### ISSUE TITLE
Feature: View comments from profile

### ISSUE THREAD

**Issue by Luminiscental** [apollo-dw/omdb#5]
Should be able to see the comments a user has made from their profile page, imo a really desirable feature.

**Comment by ryanding1** [comment]
not totally related, but I also think comments should also include how a user rated it if applicable.

**Comment by apollo-dw** [comment]
100% agree, will be one of the first things I touch on when I have time

> not totally related, but I also think comments should also include how a user rated it if applicable.
this needs some thought of me on how to display because of set comment -> difficulty rating... not sure if average is the best option or something else.

**Comment by apollo-dw** [comment]
added
