### ISSUE TITLE
Comment character limit UX

### ISSUE THREAD

**Issue by Luminiscental** [apollo-dw/omdb#56]
If I enter just `[` in the comment box, then the post button cannot be clicked. If I enter the following strings, then it posts but the comment does not appear:
- `[a`
- `[ab`
- `[abc`

However `[abcd` can be commented normally.

**Comment by Luminiscental** [comment]
Actually there is just a 5 character minimum for comments. But the 2-4 character cases should probably be the same as the 1 character case with not letting you post, rather than failing invisibly, so I'm leaving this open.

**Comment by Luminiscental** [comment]
Also garvantuur mentions that this can be entirely circumvented by adding trailing spaces, so I'm not sure if the limit actually serves any purpose. (Is it an intentional thing or just a technicality?)

**Comment by iptq** [comment]
Yeah looks like the [server][1] has a different limit than the [client][2].
Should be a pretty simple fix, just put the same numbers in both places.

Long term it might be good to put these as constants somewhere more global so
they can agree by definition.

[1]: https://github.com/apollo-dw/omdb/blob/53c250bb07c77b5a77a5339715f1539062d64b77/mapset/SubmitComment.php#L10
[2]: https://github.com/apollo-dw/omdb/blob/53c250bb07c77b5a77a5339715f1539062d64b77/mapset/index.php#L283

**Comment by Luminiscental** [comment]
So things to do are:
- Make client and server side agree on the limit
- Trim trailing whitespace from comments
- Look into why `[ab` and `xab` behave differently

**Comment by apollo-dw** [comment]
This should be a lot better now. Whitespaces are trimmed and limits now match.

**Comment by Luminiscental** [comment]
There's a remaining quirk that `[a` posts but doesn't appear, while `xa` correctly doesn't post:
![](https://luminiscental.s-ul.eu/zogp6ATy)

**Comment by apollo-dw** [comment]
fixed, symbols were being encoded into their URL form before the text length was being checked
