### ISSUE TITLE
Loved maps don't appear in "recently ranked beatmaps" on front page

### ISSUE THREAD

**Issue by apollo-dw** [apollo-dw/omdb#57]
https://twitter.com/funnyosu/status/1631003327902220525

Pretty sure this is because the query for it is based off of the date ranked column, instead of date added

**Comment by iptq** [comment]
Maybe it's worth it to just fill in `date_ranked` as the day it was loved, for
loved maps? This shouldn't be too hard to tweak in the beatmap retrieval script
and we can just run it again for current loved maps.

**Comment by apollo-dw** [comment]
Users wanted loved maps to appear on the submitted year's charts rather than the year it was loved's charts, so I don't think we want to do that. I think this might actually just be as simple as using the table's `Timestamp` column instead?

**Comment by iptq** [comment]
Ohhh I see.. ok yeah could make that change as well. I'll update the retrieval script to record that.

**Comment by apollo-dw** [comment]
Working now
