### ISSUE TITLE
Beatmap icons have empty links in user's specific ratings

### ISSUE THREAD

**Issue by Luminiscental** [apollo-dw/omdb#62]
The /profile/ratings/?id=blah&r=blah pages have empty links on the beatmap icons:
![](https://luminiscental.s-ul.eu/3G3Ka4m4)

**Comment by visionaryww** [comment]
thought he fixed this but i mentioned this on discord, https://github.com/apollo-dw/omdb/blob/master/profile/ratings/index.php line 88 should just replace `<?php echo $setID; ?>` with `<?php echo $beatmap[0]; ?>`

**Comment by apollo-dw** [comment]
I think I fixed it manually on live at one point, and then overwrote it when pushing changes. Should be fixed now anyways
