### ISSUE TITLE
MAP OF THE WEEK

### ISSUE THREAD

**Issue by VINXIS** [apollo-dw/omdb#71]
Highest rated OR ranked map of the week, deriving the idea off of [dsco's series](https://www.youtube.com/watch?v=TeuG_PYObbA&list=PLvlfixeOECIx-FBXKyjO3ttsNe4I3jHO1)

Could even have like an autoplay of it on the side or something but that's probably too much work for a random ass idea

**Comment by apollo-dw** [comment]
![image](https://github.com/apollo-dw/omdb/assets/83023433/454f1ab3-4b1a-460c-a36c-75a630a11b9c)

hopefully this will suffice. the display is a bit empty at the moment but eventually it'll have more info (like nominators)
