### ISSUE TITLE
Viewing users who have logged in but have rated 0 maps while you yourself are logged out bugs out the page

### ISSUE THREAD

**Issue by VINXIS** [apollo-dw/omdb#73]
at least that's the common pattern i'm seeing

see https://omdb.nyahh.net/profile/3513559 

![image](https://github.com/apollo-dw/omdb/assets/18523454/eaa33339-85a0-4490-9eb6-c7e4b557662e)

**Comment by tilda** [comment]
i dont know charles' github so i cant ping him here but he had a similar issue with [Okoratu's profile](https://omdb.nyahh.net/profile/1623405)

on the other hand personally i'm unable to reproduce on both of these with the latest version of firefox

**Comment by apollo-dw** [comment]
I can finally reproduce this. This is something to do with not being logged in. Remove all cookies and access the page again for reproduction.

**Comment by VINXIS** [comment]
Charles probably said this already but https://omdb.nyahh.net/profile/?id=3513559 works for the record, but if u dont specify the query param `id` explicitly it breaks (aka https://omdb.nyahh.net/profile/3513559 the original link I posted in op)

**Comment by apollo-dw** [comment]
Sorry for taking years - this has now been fixed
