### ISSUE TITLE
Add Rating Count per Category in Stats

### ISSUE THREAD

**Issue by VINXIS** [apollo-dw/omdb#77]
idk maybe show it in the tooltip or something 
![image](https://github.com/apollo-dw/omdb/assets/18523454/cce8e689-debe-45b2-8f2d-22c7536164a5)

Cuz I think it helps in digesting the information that shows in this page, as an example if I have WAY more ratings for 2023 than for the other year then that adds context to a much lower/higher rating compared to another year

**Comment by apollo-dw** [comment]
I've added it to the tooltip for now
