### ISSUE TITLE
Show more maps on the descriptor page

### ISSUE THREAD

**Issue by totallywaffles** [apollo-dw/omdb#88]
![image](https://github.com/apollo-dw/omdb/assets/87472458/4ed1da11-cb44-45ec-959c-e65e0d4dab20)

currently on this page you can only see 9 maps which kinda sucks, so I think you should make it show a lot more. Maybe it could be made so you can scroll to the right, or it could be revamped to be more like the charts page with multiple pages of maps

**Comment by apollo-dw** [comment]
added a "see more" link which takes you to the chart page with that descriptor applied
