### ISSUE TITLE
Graved sets' status not updating upon getting ranked

### ISSUE THREAD

**Issue by Sanch-KK** [apollo-dw/omdb#94]
So basically if the map was added to the site in graved state and gets ranked later it still shows as graved, while displaying nominator data, example: https://omdb.nyahh.net/mapset/1938895

Possible solution may be running a check when graved map gets rated and if it somehow gets ranked just add it to the front page etc, reset ratings probably? Shouldn't be heavy resource-wise

**Comment by apollo-dw** [comment]
Thankfully I have a script nearly ready for this, just undergoing some testing :]

**Comment by apollo-dw** [comment]
Should be resolved now.
